trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - .vscode/*
      - appveyor.yml
      - CHANGELOG.md
      - CONTRIBUTING.md
      - README.md
      - .editorconfig
      - azure-pipelines.yml
  tags:
    exclude:
      - v*

pr:
  - master

stages:
  - stage: Windows_Tests_PS
    displayName: "Windows - PS"
    dependsOn: []
    jobs:
      - job: PesterTests
        pool:
          vmImage: windows-latest
        steps:
          - powershell: |
              Install-Module -Name InvokeBuild -Force
              Install-Module -Name PSDepend -Force
              Invoke-PSDepend -Force
              Invoke-Build
            displayName: "Build and Test - Windows PowerShell"
          - task: PublishTestResults@2
            inputs:
              testRunner: "NUnit"
              testResultsFiles: "**/testResults.xml"
              testRunTitle: "ps_winLatest"
  - stage: Windows_Tests_PWSH
    displayName: "Windows - PWSH"
    dependsOn: []
    jobs:
      - job: PesterTests
        pool:
          vmImage: windows-latest
        steps:
          - pwsh: |
              Install-Module -Name InvokeBuild -Force
              Install-Module -Name PSDepend -Force
              Invoke-PSDepend -Force
              Invoke-Build
            displayName: "Build and Test - Windows PWSH"
          - task: PublishTestResults@2
            inputs:
              testRunner: "NUnit"
              testResultsFiles: "**/testResults.xml"
              testRunTitle: "pwsh_winLatest"
